name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
            SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
            # 注意替换为你的 GitHub 源仓库地址
            source-repo: "git@github.com:tidys/game-tools.git"
            destination-repo: "git@gitee.com:tidys/game-tools.git"

      - name: Gitee Pages Action
      # uses: yanglbme/gitee-pages-action@a813811f52ed4f53010702a528b72053bd04685f
        uses: yanglbme/gitee-pages-action@main
        with:
          # The Gitee username, like yanglbme
          gitee-username: ${{ secrets.GITEE_REPO }} # optional
          # The Gitee password
          gitee-password: ${{ secrets.GITEE_PWD }} # optional
          # The Gitee repository, like doocs/leetcode
          gitee-repo:  tidys/game-tools
          # Which branch to build
          branch: main # optional, default is master
          # Use force https or not
          https: false # optional, default is true
